set -g default-shell /bin/zsh
set -g mouse on

set -g pane-border-lines single
set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=colour45"
set -g pane-border-status top
set -g pane-border-format " #{?pane_active,ACTIVE,idle} #{pane_index} #{pane_current_command} "
set -g pane-border-indicators both

setw -g window-style "fg=terminal,bg=colour235"
setw -g window-active-style "fg=terminal,bg=terminal"
